### ISSUE TITLE
Android 8.1  Oreo Notification Issue 

### ISSUE THREAD

**Issue by abhayJaiswal200** [AnchorFreePartner/caketubesdk-demo-android#1]
I have got error and App crash when will i run on 8.1 Oreo device . I have search but i think this is OS version issue 8.1 with Oreo . I think it is notification relevant issue . 

Error Log:- 

 android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=My channel pri=0 contentView=null vibrate=null sound=null defaults=0x0 flags=0x42 color=0x00000000 vis=PRIVATE)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
        at android.os.Handler.dispatchMessage(Handler.java:106)

**Comment by salaheddinegit** [comment]
same issue here

**Comment by oxy9en** [comment]
Please use the last Unify version SDK with OpenVPN and Hydra protocols.
