### ISSUE TITLE
Connection broken error: in the project update to targetSdkVersion 29

### ISSUE THREAD

**Issue by MS0054** [AnchorFreePartner/caketubesdk-demo-android#7]
Hi Dears

according to Google Play's target API level 29 requirement
i changed the targetSdkVersion form 28 to 29, but I got this error

**sign_error**
Unable to connect: Connection broken

Do you think there is a way to solve this problem?

**Comment by olexandr-tymoshenko** [comment]
Hello.
This sdk does not support targeting API 29. Please switch to new sdk
https://pango.gitbook.io/pango-platform/sdk/vpn-sdk-for-android
